//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Tampinhas.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Project))]
    [KnownType(typeof(Place))]
    public partial class Organization
    {
        public Organization()
        {
            this.Projects = new HashSet<Project>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Address { get; set; }
        [DataMember]
        public int DistrictId { get; set; }
        [DataMember]
        public int CountyId { get; set; }
        [DataMember]
        public string Location { get; set; }
        [DataMember]
        public string Phone { get; set; }
    
        [DataMember]
        public virtual ICollection<Project> Projects { get; set; }
        [DataMember]
        public virtual Place District { get; set; }
        [DataMember]
        public virtual Place County { get; set; }
    }
    
}
