//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Tampinhas.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(User))]
    [KnownType(typeof(Project))]
    public partial class ProjectComment
    {
        [DataMember]
        public int UserId { get; set; }
        [DataMember]
        public string Comment { get; set; }
        [DataMember]
        public int ProjectId { get; set; }
        [DataMember]
        public System.DateTime ComentDate { get; set; }
    
        [DataMember]
        public virtual User User { get; set; }
        [DataMember]
        public virtual Project Project { get; set; }
    }
    
}
