//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Tampinhas.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(User))]
    [KnownType(typeof(Organization))]
    [KnownType(typeof(StatusType))]
    [KnownType(typeof(ProjectComment))]
    [KnownType(typeof(ProjectStatusChange))]
    public partial class Project
    {
        public Project()
        {
            this.ProjectComment = new HashSet<ProjectComment>();
            this.ProjectStatusChange = new HashSet<ProjectStatusChange>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string BenefiterName { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public int CreatorId { get; set; }
        [DataMember]
        public int OrganizationId { get; set; }
        [DataMember]
        public int StatusTypeId { get; set; }
        [DataMember]
        public string ResponsibleName { get; set; }
        [DataMember]
        public int RaisedAmmount { get; set; }
        [DataMember]
        public int TotalAmmountRaise { get; set; }
        [DataMember]
        public System.DateTime CreationDate { get; set; }
        [DataMember]
        public System.DateTime ModifiedDate { get; set; }
    
        [DataMember]
        public virtual User User { get; set; }
        [DataMember]
        public virtual Organization Organization { get; set; }
        [DataMember]
        public virtual StatusType StatusType { get; set; }
        [DataMember]
        public virtual ICollection<ProjectComment> ProjectComment { get; set; }
        [DataMember]
        public virtual ICollection<ProjectStatusChange> ProjectStatusChange { get; set; }
    }
    
}
