//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Tampinhas.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Project))]
    [KnownType(typeof(ProjectComment))]
    public partial class User
    {
        public User()
        {
            this.Projects = new HashSet<Project>();
            this.ProjectComment = new HashSet<ProjectComment>();
        }
    
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public bool Active { get; set; }
        [DataMember]
        public string Name { get; set; }
    
        [DataMember]
        public virtual ICollection<Project> Projects { get; set; }
        [DataMember]
        public virtual ICollection<ProjectComment> ProjectComment { get; set; }
    }
    
}
